### ISSUE TITLE
Store CV in cells.

### ISSUE THREAD

**Issue by Rapthera** [Nividica/ThaumicEnergistics#121]
Any chance of this happening, storing CV in some kind of energy container?

would be nice.

**Comment by Nividica** [comment]
Something similar is on the todo list, however finding strong footing for balance is an issue. I would like to add the ability for the vis-p2p to also export vis, instead of the current setup which is input only. However I fell the inclusion of any of vis storage within the network would upset the balance if it could be exported.
I may end up adding both with built-in checks to ensure that stored vis can not be exported into a relay network.
The current plan is to use a block that would amount to a Wand Locker. Wands, staves, or scepters stored in the locker would be charged or drained via the p2p network. I also don't feel that storing vis, which is more or less pure energy, in a digital medium is good solution, as the premise of the AE storage sub-system is to store physical objects digitally as energy. And while the AE power sub-system can store energy, that energy is not compatible with vis.
See issue #68 for more details.
