### ISSUE TITLE
Essentia ME Interface block

### ISSUE THREAD

**Issue by Saereth** [Nividica/ThaumicEnergistics#124]
Having an ME interface block to allow subnetting essentia storage would be extremely helpful

**Comment by Nividica** [comment]
Attaching a me storage bus to the ME interface allows the utilization of a subnet

**Comment by Nividica** [comment]
Correction: attaching an *Essentia storage bus to the ME interface

**Comment by Saereth** [comment]
Ok so I did that, but it will not pull from the alembics like that, here is a couple screenshots explaining the issue:
http://imgur.com/a/j4VZS

If instead of leaving the 4k essentia storage in the main network, I move a dedicated drive and hook it to the same network as the alembic it immediately pulls from the alembic into the drive. So it seems like even though I can see the essentia on the network and access it fully, the import bus does not see it as a valid location? 

I may be doing something wrong here or this may be a valid issue so trying to clear it up, if you need any more info or screenshots I'll be happy to provide.

**Comment by Nividica** [comment]
It is a difficult to tell from your screenshots, but you may have the interface and storage bus backwards.
Keep this in mind: Devices on a subnet can not see storage in the main net. The storage list only travels in one direction, from subnet to main net. Thats not to say that what is being stored can't travel both directions, rather the possible destinations for it. I will include some screenshots to clairfy.

In the first picture both the terminal and import bus are on the main net, and can interact with the essentia stored in the subnet.
![valid1](https://cloud.githubusercontent.com/assets/1585989/5804427/c8dc408e-9fd3-11e4-834a-c9eba8389557.jpg)

In the second picture the terminal is on the main net, but the import bus is now on the subnet. Both devices can still interact with the storage.
![valid2](https://cloud.githubusercontent.com/assets/1585989/5804428/c8ea1ae2-9fd3-11e4-8fb4-758de0745569.jpg)

In the third picture, the interface and the storage bus have swapped sides. Now the storage is on the main net, and the terminal and import bus are on the subnet. Since a subnet can no see storage on the main net, neither the import bus nor the terminal can interact with it.
![invalid](https://cloud.githubusercontent.com/assets/1585989/5804426/c8d3786e-9fd3-11e4-89e3-d8c118bdead1.jpg)

So just remember that storage drives are only visible if they are on the same network as the device, or in a subnetwork of the network they are part of.

**Comment by Saereth** [comment]
ok so going by the pictures above, using picture 1 as an example I have the drive bay on the right (Main net) and the storage bus is on the left side of the interface where the alembics are. If I put the essentia access terminal on the left (subnetwork) I can put in and pull out essentia manually, but the import bus wont import to it. If I move the drive bay to the left (subnet) then the alembic will pull and put the essentia into it. 

I decided to mirror the setup in image one and moved the drives onto the subnet with the alembics and it works (after reversing the storage bus location). not sure why it wont pull if the drives are on the main network but the essential is still visible and intractable via the terminal on both the main and subnetwork. Although it works through the essentia terminal when the drives are outside of the subnet the import bus doesnt import. 

For now I'm fine just moving my drives into the same subnet with the alembics though, ty for your fast responses, very impressed with your mod overall!
