### ISSUE TITLE
Wand Focus: AE2 Wrench to use Crescent Hammer when available

### ISSUE THREAD

**Issue by runfalk** [Nividica/ThaumicEnergistics#136]
Since the Crescent Hammer (for Thermal Expansion) is a much more powerful wrench than Certus Quartz Wrench, it would be useful for the Wrench focus to use that one when it is available.

Example of blocks not compatible with Certus Quartz wrench:

- Thermal Expansion machines (seems they can be rotated but not picked up)
- MineFactory Reloaded machines
- Slabs can't be flipped
- Chests can't be rotated
- Stairs can be rotated it seems but rotation is not consistent it seems

I understand the focus of the mod is to be a Thaumcraft <-> AE2 bridge. However, not being compatible with MFR and TE makes the foci much less useful in modpacks.

**Comment by Nividica** [comment]
Thanks for the suggestion :+1: 

While I agree that the focus looses a lot of its appeal in large-mod packs, there are a few issues that I face with expanding it.
1) It was put into the mod at the request of players who primary play magic-only + AE, and was heavily coded to interact with AE only.

2) It was rushed out the door and did not get nearly as much testing as it needed. The existing issues need to be ironed out before I can add to it. Turns out figuring out what the player is looking at is devlishly difficult for multipart and partial blocks.

3) I would have to make the Crescent Hammer a soft dependency for those who do not play a pack with it included. The existing code ~could~ make this really simple, but again its hard to say what it will look like once I get the bugs squashed.

4) This could open a floodgate for supporting a wide array of tools. Some will want support for X and others for Y, be it because they prefer one, or that their pack doesn't have what is currently supported. With that in mind I will need to give it a solid robustness for supporting more than just the AE wrench. This could lead to developing a system/way to change the tool in-game to a players preference.

5) I have no idea where I would go with the focus upgrades. Currently planned is an upgrade that will change the internal tool to the network tool and allow you to see the network status. However, if I provide a way for the player to choose the tool, then I will just scrap upgrades and leave it in their hands.

I will certainly leave this on the table, as I would love to see it moved from a novelty item to a useful tool. However as I have mentioned on the forums, my time is sorely limited until summer so I will be unable to really work on it until that point.

**Comment by runfalk** [comment]
Thank you for the reply.

For focus upgrades you could always reduce the cost for casting it, and make base cost a bit bigger. think the current base cost can be raised without issues, since one doesn't generally wrench that many things at once.

I think it will be better to keep different tools as different foci. I would really like to see a memory card foci as well. The network tool might be a differnt case and make most sense as a wrench upgrade, since it is a wrench on steroids. For a memory card foci, one possible upgrade may be storing multiple links at once, a feature I would've liked more than once.

Just throwing ideas out.
