### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by YoloDavid** [Nividica/ThaumicEnergistics#144]
When i start the game it crashes while loading.
I am ussing Thaumcraft 4.2.3.5, Appliedenergistics 2 RV2 Beta 8 and ThaumicEnergistics 0.8.9.0B RV2.

Link: http://pastebin.com/L5JvCd2D

**Comment by OldOpa** [comment]
Did you try with the latest AE2? Quite a lot of stuff changed and it works fine for me.

**Comment by YoloDavid** [comment]
I just tried updating AE2 to beta 13, but Minecraft still crashes while loading. I think that it is some kind of incapability with another mod because in FTB Infinitie it works just fine. I just cant figure out which mod it is.

**Comment by OldOpa** [comment]
try http://minecraft.curseforge.com/mc-mods/228513-loading-profiler. It is used to display the loading time of the installed mods. Maybe it will show at which point minecraft dies.

**Comment by Nividica** [comment]
The issue from the crash log is that the second item for the Vis Relay Interface recipe is null
"Invalid shapeless ore recipe: 1xitem.ItemShard@6, null, 1xthaumicenergistics.item.aeparts@6"
The items is the ME P2P Tunnel. Which means it has been somehow been disabled, or something else is going on.
From your update it seems this problem is no longer present after you updated. But I will leave this open just to be sure.
