### ISSUE TITLE
Ability To Automate Infusion

### ISSUE THREAD

**Issue by TheLMiffy1111** [Nividica/ThaumicEnergistics#159]
I was thinking that Infusion is a bit annoying, with all the instability and stuffs, so I was thinking that a way to automate Infusion would be good.
2 ideas:
1. Make a new block called the "Infusion Programmer", and a new mode in the Knowledge Inscriber. The Programmer searches the nearest Runic Matrix and anything that is needed for the infusion that is in range, including a Infusion Provider. It will determine what Infusions it can and safe to do in the Knowledge Core and only do those.
2. Make a new Forbidden Research for a new block that does Infusion in it, and still a new mode in the Knowledge Inscriber. The new block can be Infused with stuff to add Stability, each level gets more dangerous. It will also determine what Infusions it can and safe to do in the Knowledge Core and only do those
Just suggestions, and it would be awesome if it was added.

**Comment by Nividica** [comment]
Automating the infusion alter is something I decided early that I would not pursue because I feel it is at odds with, and breaks the core feeling of Thaumcraft.
However, in regards to your first suggestion, I have something in mind that's been on the 'might try' list that is similar to what you have described.
Functionally it would serve as an information source for determining the amount of environmental stability and instability. What I have envisioned is an item of some kind where you can right-click on the matrix and it would give you detailed information about where symmetry is broken, what objects are providing stabilization, and possible an indicator of the highest recommended crafting-instability. This would allow the player to fine-tune their infusion area, locating hidden sources of instability such as a misplaced cobblestone in an otherwise all dirt foundation under the floor, as well as prepare themselves for increasingly unstable recipes.
As of yet is has not come off of the drawing board, and if implemented would likely be released in a features patch in the upcoming summer months following the completion of the power generation system.
I have also considered adding passive stabilizing blocks, such as the mixed crystal cluster, that can be crafted using AE materials. The first thing that comes to mind is praecantatio infused quartz crystal clusters. But I have not ruled out the possibility of active stabilizers, which would attempt to draw power from the AE system to offset/combat instability for those situations where its impractical to dedicate the full 25x25 horizontal plane just to the infusion area.

Thank you for your suggestions :D
