### ISSUE TITLE
Import Bus not drawing from Advanced Alchemical Furnace

### ISSUE THREAD

**Issue by Wyrrrd** [Nividica/ThaumicEnergistics#207]
Not sure if this is intended, but my AAF does not give its essentia contents to my AE network. I have a configured Storage Bus with Void Jar for every possible essentia type hooked up to this, and everything has free channels. So there should be no storage problem.

Annoying part is that it worked. I did just put in OpenCCSensors (which has nothing to do with either  TC or TE) and now it doesn't.

![2015-06-24_18 31 06](https://cloud.githubusercontent.com/assets/11527443/8335763/f6e7b6c4-1a9f-11e5-85ac-9cdabe879294.png)

**Comment by Nividica** [comment]
I've only run into this one time, and I ended up having to dismantle the furnace to get it to work again. I could not even get a tube/buffer and empty jar to pull it out. However, I have seen where other people use a decanting golem to extract essentia from the furnace, and deposit it into an essentia provider. Might be worth a shot if this continues to crop up.
If/when it happens to me again I should have a much better idea of what the problem is, and if there is anything I can do to fix it.

**Comment by Wyrrrd** [comment]
Thanks for the fast reply.
The problem is that my machine is not able to maintain a lag-free server, so sadly i cannot use golems.
But I guess I won't use this construct anymore until I get a better PC...

**Comment by Nividica** [comment]
The 0.8.10.6 build should have corrected this issue.

**Comment by Tascavengur** [comment]
Still have this issue ... Had it in the past as well. When you "overload" the AAF it just stops outputting. Tried jars / removed, added the essentia import bus... The sides show a filled up purple bar on the AAF and there is some purple juice in the input.
FTB Infinity evolved expert. Thaum 4.2.3.5, Thaum NEI plugin 1.7.10-1.7a, Thaumic Energistics 1.0.0.1, Thaumic energistics core 0.10.0.0, Thaumic Tinkerer 2.5-1.7.10-512, Thaumic Tinkerer Core 0.1 (all with 0 child mods).

I'm still waiting for my hungry node to be converted and used on the AAF. If its because i have not enough CV then why did it work in the first place?

**Comment by Nividica** [comment]
There was an issue in ThE that could cause devices to fail to import from the AAF when it was in a vaild state, which was corrected in 0.8.10.6; However on occasions I would still run into a situation where the AAF becomes invalid and, as you mentioned, even using jars will not extract the essentia. I have no idea what causes it to up and stop working, but it is not an issue I have run into in a very long time, as I switched to using alchemical golems with the wifi backpacks when I implemented them, and so far have not seen the issue again. I do not recall if there were any changes to my CV source in the interim. 
If the new node doesn't fix it, you may consider using golems, with or without backpacks. If not using backpacks, the 'easiest' way to deal with getting essentia into the network is to have the golems deposit the essentia into an essentia provider.
