### ISSUE TITLE
Crash when shift-click nei recipe

### ISSUE THREAD

**Issue by oks1998** [Nividica/ThaumicEnergistics#210]
http://pastebin.com/X4x6KErV

crash when sift-click the essential storage recipe in the thaumcraft's crafting table...(crash in storage housing only and the finished storage item like 1K storage)

**Comment by Nividica** [comment]
I have tested this with many different recipes, and it seems the issue is stemming from the recent changes to Thaumcraft NEI Plugin. It seems the handler doesn't properly support modded items, as pretty much everything I tried from AE in the table also causes the crash.
[On the TNP forum neros64](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2237271-1-6-4-1-7-10-thaumcraft-nei-plugin-nei?comment=104) has also mentioned this issue. You may want to create an issue on the [TNP issue page](https://github.com/DjGiannuzz/Thaumcraft-NEI-Plugin/issues) or mention it on the forum.

**Comment by DjGiannuzz** [comment]
https://github.com/DjGiannuzz/Thaumcraft-NEI-Plugin/issues/19
