### ISSUE TITLE
Arcane crafting terminal: right-clicking to craft a stack causes crash

### ISSUE THREAD

**Issue by charlesbevans** [Nividica/ThaumicEnergistics#290]
When I right click to craft a stack of items the game crashes.
This seems to be caused by not having enough items to craft a stack. It consumed the items on at least one occasion. It happens for regular and vis-requiring recipes.
This may be related to an undesirable behavior where there are not enough materials to craft a stack and shift-clicking causes the materials to be used up and the terminal crafts the remaining pattern.
Edit: Sorry, I'm using the version in FTB Infinity on expert mode. Nothing has been modified.

**Comment by mrabenhorst** [comment]
Looks like #258 
I have the same problem too.

**Comment by charlesbevans** [comment]
I just had a crash when there were enough materials, but not enough vis in the wand.

**Comment by mrabenhorst** [comment]
Ah, I can't even open it. What versions of AE2, TE, and TC are you running?

**Comment by charlesbevans** [comment]
FTB Infinity Evolved Expert SSP, no changes.
AE2 rv3-beta-5
TE 1.0.0.1
TC 4.2.3.5

**Comment by BrewAndCode** [comment]
I can confirm this is an issue.  Right click crashes the client (Not Server).  It briefly shows a 64 stack in your hand before crash.  The two times I duplicated it all source and result products were lost but vis was not removed from wand in arcane crafting terminal.

**Comment by Cyberzoid1** [comment]
I'm experiencing the same error. Rightclick on any ThaumicEnergistics terminal and client crashes.
Running AE-RV3-Beta-1 
Modpack: Resonant rise 3301
Originally running TE 0.9.1.2 then updated to TE 1.0.0.1 on both server and client. The issue is the same and present on both versions.

Exception excerpt from fml-server-latest.log [http://pastebin.com/PH5K4Ux2](http://pastebin.com/PH5K4Ux2)


I cant wait to be able to enjoy the mod. On the server we're just getting starting with thaumcraft and I would love to be able to use this mod.

**Comment by LemADEC** [comment]
Please provide the full crash logs.
Also, which version of Java are you using?

**Comment by Cyberzoid1** [comment]
my java client: V8 update 51
Server: `java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)`

Not sure how to get the crash logs. Server didnt produce any since it's not crashing.
For the client maybe I should correct myself. Its not being crashed as its being disconnected because of some packet error, also no crash log.
I'm willing to provide any info needed.

Tonight I'll get 2 others on the server to interact with the terminal and see what happens to them. and their java versions.

**Comment by LemADEC** [comment]
From what we've experienced on our pack, you need Java 1.8 to use the mod, through it's not documented nor detected.

**Comment by Cyberzoid1** [comment]
even on the server?

**Comment by LemADEC** [comment]
Server is Java 1.8. Client was 1.7 and was alone reproducing the issue, he updated to latest Java 1.8 and it fixed his issue.
Where do you see a 8.1 ?

**Comment by Cyberzoid1** [comment]
Are you talking about the minecraft version. Like im running MC1.7.10. You running minecraft 1.8?
If so that's not an option. Changing minecraft versions would require making a whole new minecraft world.
I was referring to java 7 vs 8

**Comment by Cyberzoid1** [comment]
YES! updating the server to 'java version "1.8.0_77"' did indeed work!
Granted I haven't tested much but I can access both the Arcane and Essentia terminals without getting disconnected.
Currently running mod: AE-RV3-Beta-1, Thaumic Energistics 0.9.1.2  (I reverted back to the original server mods)

Thank you for your help :+1:

**Comment by BrewAndCode** [comment]
I am running 1.8.073 and experience this issue (both client & server)

it is the client that crashes, and only when right-clicking in order to produce a full "Stack" of whatever arcane crafting I wish. 

I can left-click results to craft a single set at a time.

when I right-click to craft a full stack:

[crash-2016-04-07_18.38.49-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/209345/crash-2016-04-07_18.38.49-client.txt)

**Comment by BrewAndCode** [comment]
Sorry-- it's java 1.8.0.25 on client, 77 on server.

**Comment by LemADEC** [comment]
This ticket is about crashing when opening the GUI, which is different from crashing when crafting after GUI is open.

Update your client to 1.8.0.77 then?

**Comment by BrewAndCode** [comment]
Negative, the OP reports crash when right-clicking to craft stack.  Cyberzoid's issue was one that deviated from OP.

**Comment by charlesbevans** [comment]
I just updated to the most recent Java and I still get the crash when right-clicking to craft a stack without enough resources.
[crash-2016-04-07_15.55.01-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/209365/crash-2016-04-07_15.55.01-client.txt)

**Comment by KuzmaVolkov** [comment]
Dunno if helpful or not but this is the red text that wizes by the moment i click on the arcane cell workbench.
http://pastebin.com/kZ2yFEKC

**Comment by Lohoydo** [comment]
I can also confirm this happening every time.

[crash-2016-04-14_09.07.48-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/219181/crash-2016-04-14_09.07.48-client.txt)

**Comment by Lohoydo** [comment]
Can also happen when double clicking (from clicking too fast when single crafting or trying to also collect the ones in your inventory into the stack)

[crash-2016-04-14_09.36.19-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/219214/crash-2016-04-14_09.36.19-client.txt)

**Comment by Nividica** [comment]
This one just keeps popping up in all kinds of ways.
See #274
