### ISSUE TITLE
Essentia crafting dependencies 

### ISSUE THREAD

**Issue by CarsonF** [Nividica/ThaumicEnergistics#315]
Currently (unless I'm missing something) there's no way to specify essentia needed for crafting patterns for alchemical construct. It would be nice if AE could tell me of missing essentia instead of the item getting stuck in the AC waiting for essentia. 

I understand the struggle with having to fake those dependencies since essentia would still come from the essentia provider. 

Maybe a solution would be an essentia pattern that could go into the essentia interface. The interface on crafting request would be given limited ammount of essentia (specified from pattern) that the AC could pull. 

I havent looked into the code too much so idk about the feasibility of this. I imagine given your direction with the knowledge core it was hard to hook into AE's crafting code.

**Comment by Nividica** [comment]
There is no way that I could find to bridge the gap from a recipe needing essentia to crafting said essentia. The crafting network ONLY deals with items, and essentia is not represented as an item in the network. What little I was able to accomplish with being able to request essentia from the essentia terminal involved a lot of tricks/lies to the network. In effect, I use a placeholder item in the result, and if the essentia terminal see's that the placeholder item can be crafted, it converts it back to its essentia type and shows that the essentia can be crafted. When you actually request the item be crafted, it sets up a chain of events where the essentia network waits for the essentia amounts to begin increasing, and reports that the placeholder item arrived and was 'stored' when in-fact there were no items to begin with. It is a complicated work around that when I attempted to bridge with essentia being a dependent item in recipes, the crafting CPU's would get real pissy when the essentia 'item' wasn't being delivered to them. And even when I tried that route the placeholder items would get into the item network, then next thing you know you have 100k Essentia Ignis items clogging up some cell because the farce could not be maintained. Now, IF I wasn't lieing to the crafting network about these placeholder items, I could get it to work, but that would mean that essentia was stored as a regular old item, which could be removed from a regular terminal and then placed in a vanilla chest. Not to mention they would take up gobs and gobs of regular cell space, because, well, they are just normal items! It was alltogether very frustrating that I was never able to get the system to work like I wanted to, but the crafting system, including patterns, is hard-coded to only accept genuine items. And when a recipe calls for an item, the CPU's demand the item be stored inside of them for the duration of the crafting process, or they stop, and wait, for the item to be delivered.
